--Backout Script to just drop tables and sequences

DROP TABLE CF_USER;

DROP TABLE VENDOR;

DROP TABLE MENU;

DROP TABLE TRANSACTION;

DROP TABLE ORDER_ITEMS;

--Backout Script to drop Sequences

DROP SEQUENCE IF EXISTS VENDOR_SEQ;

DROP SEQUENCE IF EXISTS MENU_SEQ;

DROP SEQUENCE IF EXISTS TRANSACTION_SEQ;